# Generated by Django 5.2.3 on 2025-06-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_client_user_mailing_user_mailingattempt_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_mailing"],
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailings", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
